name: build

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - root/**
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - root/**
  repository_dispatch:
    types:
      - upstream_image_update

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: UT2004 Server
      GHCR_SLUG: ghcr.io/phasecorex/ut2004-server
      DOCK_SLUG: docker.io/phasecorex/ut2004-server
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v6
        with:
          script: |
            const repo = await github.rest.repos.get(context.repo)
            return repo.data
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: |
            linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_SLUG }}:latest
            ${{ env.DOCK_SLUG }}:latest
          cache-from: |
            ${{ env.GHCR_SLUG }}:latest
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.GHCR_SLUG }}:latest
          docker buildx imagetools inspect ${{ env.DOCK_SLUG }}:latest
      -
        name: Check pull
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.GHCR_SLUG }}:latest
          docker image inspect ${{ env.GHCR_SLUG }}:latest
          docker pull ${{ env.DOCK_SLUG }}:latest
          docker image inspect ${{ env.DOCK_SLUG }}:latest
